# Generated by Django 4.2.4 on 2023-09-01 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Livraria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('preco', models.CharField(max_length=20)),
                ('autor', models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='livraria.autor')),
            ],
        ),
    ]
